apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend-service
        image: gasendevops/backend-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "mysql://mysql-service:3306/devopsclass"
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "D!eng1251#"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
